modLoader="javafml"
loaderVersion="${forge_loader_version_range}" #forge version dep
license="${mod_license}"
issueTrackerURL="https://github.com/iChun/Death-Counter/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}" #mandatory
    displayName="${mod_name}"
    displayURL="https://ichun.me/mods/death-counter/"
    logoFile="icon.png"
    authors="iChun"
    description='''
    Simple death counter for servers.
    '''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
